# Generated by Django 5.0.6 on 2024-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedSong',
            fields=[
                ('songId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('songName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('songName', models.CharField(max_length=100)),
                ('recommendedSongs', models.ManyToManyField(to='song_api.recommendedsong')),
            ],
        ),
    ]
