# Generated by Django 5.0.6 on 2024-06-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedsong',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
